version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend_server:
    build: ./backend
    container_name: backend_server
    expose:
      - "5000"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/mern-user-management
      - JWT_SECRET=your_secret_key_here
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend_server
    restart: always
