version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend_server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=supersecret
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend_client
    ports:
      - '3000:80'  # nginx écoute sur le port 80, on expose sur 3000
    depends_on:
      - backend

volumes:
  mongo-data:
