name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Ajouter la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 34.60.116.64 >> ~/.ssh/known_hosts

      - name: SSH & deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 youssoundiaye_yn_yn@34.60.116.64 '
            cd ~/mern-user-management &&
            git pull --rebase=false origin main &&
            docker-compose down &&
            docker-compose up --build -d
          '
